resources:
  - ../../base

namespace: vista
patches:
  - path: patches/allow-ingress.yaml
    target:
      kind: AuthorizationPolicy
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: smart-cache-vista-api-sa

labels:
  - pairs:
      env: demo

images:
  - name: smart-cache-vista-api-image:template
    newName: 537124944113.dkr.ecr.eu-west-2.amazonaws.com/vista/smart-cache-vista-api
    newTag: "to.be.replaced"

configMapGenerator:
  - name: smart-cache-vista-api-configs
    envs:
      - params.env
