version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      actions-updates:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pip"
    directory: "/backend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      js-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "npm"
    directory: "/frontend/qa"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      js-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "docker"
    directory: "/frontend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "docker"
    directory: "/frontend/dev"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "docker"
    directory: "/backend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "docker"
    directory: "/transparent-proxy"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
