apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vista-python-api-static-secret
spec:
  refreshAfter: 30s

  # path of the secret
  path: applications/vista/python-api

  type: kv-v2

  mount: k8-cluster

  destination:
    # dest k8s secret
    name: vista-python-api-secret
    create: true

  vaultAuthRef: vista-python-api-static-auth
