[pytest]
testpaths = vista-python-api/src/api/tests
pythonpath = vista-python-api/src
DJANGO_SETTINGS_MODULE = core.settings
addopts = --cov=core --cov=api --cov-report=term-missing:skip-covered --cov-config=pyproject.toml
