[pytest]
asyncio_mode = auto
testpaths = vista-python-api/src/api/tests
pythonpath = vista-python-api/src
DJANGO_SETTINGS_MODULE = api.tests.settings
addopts = --cov=core --cov=api --cov-report=term-missing:skip-covered --cov-config=pyproject.toml
norecursedirs = lib lib64
