PREFIX ies: <http://ies.data.gov.uk/ontology/ies4#>
prefix ndt: <https://www.iow.gov.uk/DigitalTwin#>

DELETE {{ ?s ?p ?o . }} WHERE {{
  {{
    {{
      SELECT ?s (count(?s) as ?c) {{
        <{asset}> (ies:hasName | ies:inLocation | ies:isIdentifiedBy)* ?s .
        OPTIONAL {{ ?ss ?pp ?s }}
      }}
      GROUP BY ?s
    }}
    FILTER (?c = 1)
    ?s ?p ?o .
  }}
  UNION
  {{
    ?s ?p <{asset}> .
    BIND(<{asset}> AS ?o)
  }}
}}
