resources:
  - ../../base

namespace: paralog
patches:
  - path: patches/gateway.yaml
    target:
      kind: Gateway
  - path: patches/allow-ingress.yaml
    target:
      kind: AuthorizationPolicy
  - path: patches/virtualService.yaml
    target:
      kind: VirtualService
      name: paralog-transparent-proxy
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: paralog-transparent-proxy-sa

labels:
  - pairs:
      env: dev

images:
  - name: paralog-transparent-proxy-image
    newName: 537124944113.dkr.ecr.eu-west-2.amazonaws.com/paralog/transparent-proxy
    newTag: "to.be.replaced"
