apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    io.kompose.service: vista-transparent-proxy
  name: vista-transparent-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vista-transparent-proxy
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/inject: "false"
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
      labels:
        io.kompose.service: vista-transparent-proxy
    spec:
      serviceAccountName: vista-transparent-proxy-sa
      containers:
        - name: vista-transparent-proxy-image
          image: vista-transparent-proxy-image:template
          resources:
            limits:
              memory: "2Gi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
              ephemeral-storage: "2Gi"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: vista-transparent-proxy-secrets
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
