resources:
  - ../base/istio/authorizationpolicy/deny-by-default.yaml
  - ../base/istio/authorizationpolicy/allow-ingress-authorization-policy.yaml
  - ../base/istio/gateway.yaml
  - ../base/istio/virtualService.yaml
  - ../base/istio/peereauthentication.yaml
  - ../base/istio/requestAuthentication.yaml
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - VaultAuth.yaml
  - VaultStaticSecret.yaml

labels:
  - pairs:
      app: paralog-transparent-proxy
      env: ENV_PLACEHOLDER
      app.kubernetes.io/name: paralog-transparent-proxy




