apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: vista-transparent-proxy
  name: vista-transparent-proxy
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  type: NodePort
  selector:
    io.kompose.service: vista-transparent-proxy
