apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-smart-cache-vista-api
spec:
  selector:
    matchLabels:
      io.kompose.service: smart-cache-vista-api
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["PLACE_HOLDER"]
      to:
        - operation:
            methods: ["GET", "POST"]
