"""Unit tests for AssetFilterBuilder."""
# ruff: noqa: T201 - print statements are intentional for SQL visualization

import uuid
from decimal import Decimal

import pytest
from django.contrib.gis.geos import Polygon
from django.db.models import Q

from api.filters import AssetFilterBuilder, FilterContext
from api.models import AssetScoreFilter
from api.models.asset import Asset
from api.models.asset_type import AssetCategory, AssetSubCategory, AssetType, DataSource


@pytest.fixture
def asset_type_setup(db):  # noqa: ARG001
    """Create test asset types."""
    category = AssetCategory.objects.create(id=uuid.uuid4(), name="Infrastructure")
    sub_category = AssetSubCategory.objects.create(
        id=uuid.uuid4(), name="Energy", category_id=category
    )
    data_source = DataSource.objects.create(id=uuid.uuid4(), name="Test Source")

    station_type = AssetType.objects.create(
        id=uuid.uuid4(),
        name="Stations",
        sub_category_id=sub_category,
        data_source_id=data_source,
    )
    pylon_type = AssetType.objects.create(
        id=uuid.uuid4(),
        name="Pylons",
        sub_category_id=sub_category,
        data_source_id=data_source,
    )

    return {
        "category": category,
        "sub_category": sub_category,
        "data_source": data_source,
        "station_type": station_type,
        "pylon_type": pylon_type,
    }


@pytest.mark.django_db
class TestAssetFilterBuilderSQL:
    """Tests to visualize the SQL queries generated by AssetFilterBuilder."""

    def test_by_asset_type_mode_single_type_no_score_filter(
        self, scenario, asset_type_setup, mock_user_id
    ):
        """Visualize SQL for by_asset_type mode with one visible type, no score filter."""
        station_type = asset_type_setup["station_type"]

        ctx = FilterContext(
            scenario_id=scenario.id,
            user_id=mock_user_id,
            type_filters={},
            global_filter=None,
        )
        builder = AssetFilterBuilder(ctx)

        q = builder.build_by_asset_type(
            visible_type_ids={station_type.id},
            geometry=None,
        )

        queryset = Asset.objects.filter(q)
        sql = str(queryset.query)

        print("\n" + "=" * 80)
        print("by_asset_type mode - single type, no score filter")
        print("=" * 80)
        print(sql)
        print("=" * 80 + "\n")

        assert "type_id" in sql
        assert str(station_type.id) in sql

    def test_by_asset_type_mode_with_score_filter(self, scenario, asset_type_setup, mock_user_id):
        """Visualize SQL for by_asset_type mode with score filter on a type."""
        station_type = asset_type_setup["station_type"]

        score_filter = AssetScoreFilter(
            focus_area_id=uuid.uuid4(),
            asset_type=station_type,
            criticality_values=[2, 3],
            exposure_values=[0, 1],
            dependency_min=Decimal("1.0"),
            dependency_max=Decimal("5.0"),
        )

        ctx = FilterContext(
            scenario_id=scenario.id,
            user_id=mock_user_id,
            type_filters={station_type.id: score_filter},
            global_filter=None,
        )
        builder = AssetFilterBuilder(ctx)

        q = builder.build_by_asset_type(
            visible_type_ids={station_type.id},
            geometry=None,
        )

        queryset = Asset.objects.filter(q)
        sql = str(queryset.query)

        print("\n" + "=" * 80)
        print("by_asset_type mode - with criticality, exposure, dependency score filter")
        print("=" * 80)
        print(sql)
        print("=" * 80 + "\n")

        assert "asset_scores" in sql
        assert "criticality_score" in sql
        assert "exposure_score" in sql
        assert "dependency_score" in sql

    def test_by_asset_type_mode_multiple_types_mixed_filters(
        self, scenario, asset_type_setup, mock_user_id
    ):
        """Visualize SQL for multiple types with different filter configurations."""
        station_type = asset_type_setup["station_type"]
        pylon_type = asset_type_setup["pylon_type"]

        station_filter = AssetScoreFilter(
            focus_area_id=uuid.uuid4(),
            asset_type=station_type,
            criticality_values=[3],
        )

        ctx = FilterContext(
            scenario_id=scenario.id,
            user_id=mock_user_id,
            type_filters={station_type.id: station_filter},
            global_filter=None,
        )
        builder = AssetFilterBuilder(ctx)

        q = builder.build_by_asset_type(
            visible_type_ids={station_type.id, pylon_type.id},
            geometry=None,
        )

        queryset = Asset.objects.filter(q)
        sql = str(queryset.query)

        print("\n" + "=" * 80)
        print("by_asset_type mode - two types, only one with score filter")
        print("=" * 80)
        print(sql)
        print("=" * 80 + "\n")

        assert str(station_type.id) in sql
        assert str(pylon_type.id) in sql

    def test_by_score_only_mode_no_filter(self, scenario, mock_user_id):
        """Visualize SQL for by_score_only mode without any criteria."""
        ctx = FilterContext(
            scenario_id=scenario.id,
            user_id=mock_user_id,
            type_filters={},
            global_filter=None,
        )
        builder = AssetFilterBuilder(ctx)

        q = builder.build_by_score_only(geometry=None)

        queryset = Asset.objects.filter(q)
        sql = str(queryset.query)

        print("\n" + "=" * 80)
        print("by_score_only mode - no filter criteria (returns all scored assets)")
        print("=" * 80)
        print(sql)
        print("=" * 80 + "\n")

        assert "asset_scores" in sql

    def test_by_score_only_mode_with_global_filter(self, scenario, mock_user_id):
        """Visualize SQL for by_score_only mode with global filter criteria."""
        global_filter = AssetScoreFilter(
            focus_area_id=uuid.uuid4(),
            asset_type=None,
            criticality_values=[2, 3],
            redundancy_values=[3],
            dependency_min=Decimal("0.0"),
            dependency_max=Decimal("10.0"),
        )

        ctx = FilterContext(
            scenario_id=scenario.id,
            user_id=mock_user_id,
            type_filters={},
            global_filter=global_filter,
        )
        builder = AssetFilterBuilder(ctx)

        q = builder.build_by_score_only(geometry=None)

        queryset = Asset.objects.filter(q)
        sql = str(queryset.query)

        print("\n" + "=" * 80)
        print("by_score_only mode - with global filter (criticality, redundancy, dependency)")
        print("=" * 80)
        print(sql)
        print("=" * 80 + "\n")

        assert "asset_scores" in sql
        assert "criticality_score" in sql
        assert "redundancy_score" in sql
        assert "dependency_score" in sql

    def test_with_geometry_filter(self, scenario, asset_type_setup, mock_user_id):
        """Visualize SQL when geometry filter is applied."""
        station_type = asset_type_setup["station_type"]
        geometry = Polygon([(0, 0), (10, 0), (10, 10), (0, 10), (0, 0)])

        ctx = FilterContext(
            scenario_id=scenario.id,
            user_id=mock_user_id,
            type_filters={},
            global_filter=None,
        )
        builder = AssetFilterBuilder(ctx)

        q = builder.build_by_asset_type(
            visible_type_ids={station_type.id},
            geometry=geometry,
        )

        queryset = Asset.objects.filter(q)
        sql = str(queryset.query)

        print("\n" + "=" * 80)
        print("by_asset_type mode - with geometry filter (ST_Within)")
        print("=" * 80)
        print(sql)
        print("=" * 80 + "\n")

        assert "ST_Within" in sql or "geom" in sql

    def test_with_exclude_q(self, scenario, mock_user_id):
        """Visualize SQL when exclusion Q is applied (map-wide excluding focus areas)."""
        exclude_geometry = Polygon([(0, 0), (5, 0), (5, 5), (0, 5), (0, 0)])
        exclude_q = Q(geom__within=exclude_geometry)

        ctx = FilterContext(
            scenario_id=scenario.id,
            user_id=mock_user_id,
            type_filters={},
            global_filter=None,
        )
        builder = AssetFilterBuilder(ctx)

        q = builder.build_by_score_only(geometry=None, exclude_q=exclude_q)

        queryset = Asset.objects.filter(q)
        sql = str(queryset.query)

        print("\n" + "=" * 80)
        print("by_score_only mode - with exclusion Q (NOT ST_Within)")
        print("=" * 80)
        print(sql)
        print("=" * 80 + "\n")

        assert "NOT" in sql or "not" in sql.lower()
