services:
  cack-adder:
    container_name: data-adder
    depends_on:
      kafka1:
        condition: service_started
    environment:
      BOOTSTRAP_SERVERS: kafka1:19092
      CACK_ADDER_PORT: "8079"
      CLEAN_ENTITY_TOPIC: clean-entity
      DEFAULT_DATA_URI_STUB: http://telicent.io/fake_data#
      ES_CLUSTER_HOST: es01
      ES_CLUSTER_PORT: "9200"
      ES_CLUSTER_PROTOCOL: http
      FAKE_INSURANCE_TOPIC: fake-insurance
      GEO_CLEAN_TOPIC: geo-clean
      IES_TOPIC: knowledge
      JENA_DATASET: knowledge
      JENA_PORT: "3030"
      JENA_URL: telicent-jena-smart-cache
    image: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-cack-adder:0.1.4
    networks:
      - paralog_dev
    ports:
      - mode: ingress
        target: 8079
        published: 8079
        protocol: tcp
    restart: on-failure
  configure-kafka-knowledge:
    command:
      - kafka-topics.sh
      - --bootstrap-server
      - kafka1:19092
      - --create
      - --topic
      - knowledge
      - --partitions
      - "1"
      - --replication-factor
      - "1"
    image: wurstmeister/kafka
    networks:
      - paralog_dev
  zoo1:
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_SERVER_ID: "1"
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - paralog_dev
    restart: on-failure
  kafdrop:
    depends_on:
      kafka1:
        condition: service_started
    environment:
      JVM_OPTS: -Xms32M -Xmx64M
      KAFKA_BROKERCONNECT: kafka1:19092
      SERVER_SERVLET_CONTEXTPATH: /
    image: obsidiandynamics/kafdrop:3.29.0
    networks:
      - paralog_dev
    ports:
      - mode: ingress
        target: 9000
        published: 9000
        protocol: tcp
    restart: on-failure
  kafka1:
    depends_on:
      zoo1:
        condition: service_started
    environment:
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL_DOCKER_INTERNAL://localhost:19093,LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
      KAFKA_BROKER_ID: "1"
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_JMX_HOSTNAME: 127.0.0.1
      KAFKA_JMX_PORT: "9999"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
    image: confluentinc/cp-kafka:7.2.2
    networks:
      - paralog_dev
    ports:
      - mode: ingress
        target: 19093
        published: 19093
        protocol: tcp
    restart: on-failure
  telicent-paralog-api:
    container_name: telicent-paralog-api
    depends_on:
      telicent-jena-smart-cache:
        condition: service_started
    environment:
      JENA_DATASET: knowledge
      JENA_PORT: "3030"
      JENA_URL: telicent-jena-smart-cache
      PORT: "4001"
    image: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-smart-cache-paralog-api:0.0.1
    # 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-paralog-api:carver-demo-0.2
    networks:
      - paralog_dev
    ports:
      - mode: ingress
        target: 4001
        published: 4001
        protocol: tcp
    restart: on-failure
    
  telicent-paralog-ui:
    container_name: telicent-paralog-ui
    depends_on:
      telicent-paralog-api:
        condition: service_started
    environment:
      API_URL: http://localhost:4001
      BETA: true
      # OFFLINE_STYLES: dark,light
      # OFFLINE_STYLES_BASE_URL: http://localhost:8111
      # OFFLINE_STYLES_PATH: /styles/<STYLE>/style.json
      MAPBOX_TOKEN: pk.eyJ1IjoibXJkNTA0IiwiYSI6ImNrcXkwaDY0dDA2NXkycXM2ZHY1b3VkbjcifQ.WSLCm8FHh9xj8lnZiRjdZg

    image: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-paralog:1.1.3
    ports:
      - mode: ingress
        target: 80
        published: 5001
        protocol: tcp
    restart: on-failure
    

  telicent-jena-smart-cache:
    command:
      - --config
      - /fuseki/config/config-dev.ttl
    depends_on:
      kafka1:
        condition: service_started
    environment:
      ADMIN_PASSWORD: password
    image: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/smart-cache-graph:0.5.0
    networks:
      - paralog_dev
    ports:
      - mode: ingress
        target: 3030
        published: 3030
        protocol: tcp
    volumes:
      - type: bind
        source: ./smart-cache/jena/config
        target: /fuseki/config
        read_only: true
        bind:
          create_host_path: true
networks:
  paralog_dev:
    name: paralog_dev