resources:
  - ../../base

namespace: paralog


patches:
  - path: patches/gateway.yaml
    target:
      kind: Gateway
  - path: patches/allow-ingress.yaml
    target:
      kind: AuthorizationPolicy
  - path: patches/requestAuthentication.yaml
    target:
      kind: RequestAuthentication
      name: cognito-authentication-request
  - path: patches/virtualService.yaml
    target:
      kind: VirtualService
      name: paralog-frontend
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: paralog-frontend-sa



labels:
  - pairs:
      env: demo


images:
  - name: paralog-frontend-image
    newName: 503561419905.dkr.ecr.eu-west-2.amazonaws.com/paralog/demo-frontend
    newTag: 'latest'


