"""Generated by Django 5.1 on 2024-08-22 12:00."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adjust length of name field."""

    dependencies: ClassVar = [
        ("api", "0005_lowbridge_name"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="lowbridge",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
