"""Generated by Django 5.1.1 on 2024-09-19 15:58."""

from pathlib import Path
from typing import ClassVar

from django.db import migrations

from api.load_fixture import LoadFixture

fixtures_dir = Path(__file__).resolve().parent.parent.parent / "data" / "fixtures"


class Migration(migrations.Migration):
    """Load initial data into the models."""

    dependencies: ClassVar = [
        ("api", "0011_narrowroad"),
    ]

    operations: ClassVar = [
        LoadFixture("api.narrowroad", fixtures_dir / "narrow_roads.json.gz"),
    ]
