# Generated by Django 5.1.5 on 2025-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_metricate_envelope_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='coordinates',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
