apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paralog-transparent-proxy-static-secret
spec:
  refreshAfter: 10s
  path: applications/paralog/transparent-proxy
  type: kv-v2
  mount: k8-cluster
  destination:
    name: paralog-transparent-proxy-static-secret
    create: true
  vaultAuthRef: paralog/paralog-transparent-proxy-static-auth

