apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    io.kompose.service: smart-cache-paralog-api
  name: smart-cache-paralog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smart-cache-paralog-api
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: smart-cache-paralog-api
    spec:
      serviceAccountName: smart-cache-paralog-api-sa
      containers:
        - name: smart-cache-paralog-api-image
          image: smart-cache-paralog-api-image
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: smart-cache-paralog-api-configs
          livenessProbe:
            httpGet:
              port: 4001
              path: /
            timeoutSeconds: 3
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 4001
              path: /
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: 4001
              protocol: TCP
          resources:
            requests:
              cpu: 1 # Minimum CPU your container is guaranteed.
              memory: "1Gi" # Minimum Memory your container is guaranteed.
            limits:
              cpu: 1 # Maximum CPU your container can use.
              memory: "2Gi" # Maximum Memory your container can use.
      restartPolicy: Always
