apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: smart-cache-paralog-api
  name: smart-cache-paralog-api
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 4001
  type: NodePort
  selector:
    io.kompose.service: smart-cache-paralog-api
