resources:
  - ../../base

namespace: vista
patches:
  - path: patches/allow-ingress.yaml
    target:
      kind: AuthorizationPolicy
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: vista-transparent-proxy-sa

labels:
  - pairs:
      env: prod

images:
  - name: vista-transparent-proxy-image:template
    newName: 537124944113.dkr.ecr.eu-west-2.amazonaws.com/vista/transparent-proxy
    newTag: "to.be.replaced"

configMapGenerator:
  - name: vista-transparent-proxy-configs
    envs:
      - params.env
