apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: vista-transparent-proxy-se
spec:
  hosts:
    - vista-transparent-proxy.vista.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
