"""Generated by Django 5.1 on 2024-08-15 10:54."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Longitudes go from minus 180 to plus 180 (three digits before decimal point)."""

    dependencies: ClassVar = [
        ("api", "0001_initial"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="sandbagplacement",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=9,
            ),
        ),
    ]
