"""Generated by Django 5.1 on 2024-08-20 14:25."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create a VulnerablePerson and TrafficData models."""

    dependencies: ClassVar = [
        ("api", "0002_alter_sandbagplacement_longitude"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="VulnerablePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mock_individual_index", models.CharField(max_length=255)),
                ("mock_property_index", models.CharField(max_length=255)),
                ("mock_first_name", models.CharField(max_length=255)),
                ("mock_last_name", models.CharField(max_length=255)),
                ("mock_sex", models.CharField(max_length=50)),
                ("mock_year_of_birth", models.IntegerField()),
                ("mock_disability", models.CharField(max_length=255)),
                ("mock_asc_primary_support_reason", models.CharField(max_length=255)),
                ("mock_address_line1", models.CharField(max_length=255)),
                ("mock_alert_category", models.CharField(max_length=255)),
                ("mock_alert_detail", models.CharField(max_length=255)),
                ("uprn", models.CharField(max_length=255)),
                ("postcode_locator", models.CharField(max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TrafficData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("day_of_week", models.CharField(max_length=10)),
                ("hour", models.TimeField()),
                ("direction", models.CharField(max_length=255)),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("busyness", models.IntegerField(blank=True, null=True)),
                ("average_speed", models.IntegerField(blank=True, null=True)),
                ("coordinates", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "unique_together": {
                    ("site_name", "day_of_week", "hour", "direction", "coordinates")
                },
            },
        ),
    ]
