"""Generated by Django 5.1.1 on 2024-09-19 15:11."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""

    dependencies: ClassVar = [
        ("api", "0010_alter_sandbagplacement_name"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="NarrowRoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("local_id", models.CharField(max_length=50, unique=True)),
                ("dimension_in", models.IntegerField()),
                ("direction", models.CharField(blank=True, max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
