# Generated by Django 5.1.10 on 2025-08-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_sandbagplacement_delete_vulnerableperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LowBridge',
        ),
    ]
