apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    io.kompose.service: paralog-pro-frontend
  name: paralog-pro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: paralog-pro-frontend
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: paralog-pro-frontend
    spec:
      serviceAccountName: paralog-frontend-sa
      containers:
        - image: paralog-frontend-image
          env:
            - name: IMAGE_DIGEST
              value: 'none'
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
