apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: paralog-pro-frontend
  name: paralog-pro-frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  type: NodePort
  selector:
    io.kompose.service: paralog-pro-frontend
