apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: smart-cache-paralog-pro-api-static-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: smart-cache-paralog-pro-api-role
    serviceAccount: smart-cache-paralog-pro-api-sa
    audiences:
      - vault
