services:
  graph-smart-cache:
    environment:
      JAVA_OPTIONS: "-XX:MaxRAMPercentage=70.0"
    command:
      - --ping
      - --config
      - /fuseki/config/config.ttl
    image: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/smart-cache-graph:0.60.1
    volumes:
      - ./config:/fuseki/config:ro
      - ./data:/fuseki/data:ro

    ports:
      - 3030:3030

  ontology-api:
    image: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-smart-cache-ontology:0.0.5-rc1

    ports:
      - 5007:5007
    environment:
      JENA_URL: graph-smart-cache
      JENA_PORT: 3030
      ONTO_PORT: 5007
      ONTOLOGY_SERVER_MODE: file
    restart: unless-stopped
    healthcheck:
      test: curl -X GET "http://localhost:5007/" || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    user: root

  api:
    image: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-smart-cache-paralog-api:1.1.7

    ports:
      - 4001:4001
    environment:
      JENA_URL: graph-smart-cache
      JENA_PORT: 3030
      PORT: 4001
      JENA_DATASET: knowledge
    restart: unless-stopped
    healthcheck:
      test: curl -X GET "http://localhost:4001/" || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    user: root

  transparent-proxy:
    image: paralog-transparent-proxy:latest
    ports:
      - 5013:80
    restart: unless-stopped
    env_file:
      - "../.env"
