
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: smart-cache-paralog-pro-api
spec:
  hosts:
    - placeholder
  gateways:
    - placeholder
  http:
    - match:
        - uri:
            prefix: /paralog/
      rewrite:
        uri : "/"
      route:
        - destination:
            host: smart-cache-paralog-pro-api
            port:
              number: 80
