"""Generated by Django 5.1 on 2024-08-22 11:43."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create LowBridge model."""

    dependencies: ClassVar = [
        ("api", "0003_vulnerableperson_trafficdata"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="LowBridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("local_id", models.CharField(max_length=50, unique=True)),
                ("dimension_in", models.IntegerField()),
                ("direction", models.CharField(blank=True, max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
