"""Generated by Django 5.1 on 2024-08-22 11:48."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add a name field to the LowBridge model."""

    dependencies: ClassVar = [
        ("api", "0004_lowbridge"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="lowbridge",
            name="name",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
