# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.1 on 2024-08-22 11:48."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add a name field to the LowBridge model."""

    dependencies: ClassVar = [
        ("api", "0004_lowbridge"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="lowbridge",
            name="name",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
