# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.1.1 on 2024-09-12 09:50."""

from pathlib import Path
from typing import ClassVar

from django.db import migrations

from api.load_fixture import LoadFixture

fixtures_dir = Path(__file__).resolve().parent.parent.parent / "data" / "fixtures"


class Migration(migrations.Migration):
    """Load initial data into the models."""

    dependencies: ClassVar = [
        ("api", "0006_alter_lowbridge_name"),
    ]

    operations: ClassVar = [
        LoadFixture("api.trafficdata", fixtures_dir / "traffic_data.json.gz"),
        LoadFixture("api.lowbridge", fixtures_dir / "low_bridges.json.gz"),
        LoadFixture("api.vulnerableperson", fixtures_dir / "vulnerable_person.json.gz"),
    ]
