# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.1 on 2024-09-02 17:21."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Make Sandbagplacement names unique, so they can be deleted by name."""

    dependencies: ClassVar = [
        ("api", "0007_load_initial_data"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="sandbagplacement",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
