"""Generated by Django 5.1 on 2024-09-02 17:21."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Apply Sandbagplacement latitude and longitude fields."""

    dependencies: ClassVar = [
        ("api", "0008_alter_sandbagplacement_name"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="sandbagplacement",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sandbagplacement",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
