# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.1.1 on 2024-09-13 16:22."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Convert SandbagPlacement charfield to textfield."""

    dependencies: ClassVar = [
        ("api", "0009_alter_sandbagplacement_latitude_and_more"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="sandbagplacement",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
