"""Generated by Django 5.2.6 on 2025-10-07 12:22."""

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    """Install Postgis extension."""

    dependencies: ClassVar = [
        ("api", "0016_delete_lowbridge"),
    ]

    operations: ClassVar = [
        migrations.RunSQL(
            sql=[
                "CREATE EXTENSION IF NOT EXISTS postgis;",
            ],
            reverse_sql=[
                "DROP EXTENSION IF EXISTS postgis;",
            ],
        ),
    ]
