# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.6 on 2025-10-08 13:31."""

from typing import ClassVar

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create a minimal Asset Model."""

    dependencies: ClassVar = [
        ("api", "0017_enable_postgis"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="AssetSubCategory",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.assetcategory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "sub_category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.assetsubcategory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.assettype"
                    ),
                ),
            ],
        ),
    ]
