# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.6 on 2025-10-14 15:33."""

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create a minimal Dependency Model."""

    dependencies: ClassVar = [
        ("api", "0018_create_asset_tables"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "dependent_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent",
                        to="api.asset",
                    ),
                ),
                (
                    "provider_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider",
                        to="api.asset",
                    ),
                ),
            ],
        ),
    ]
