# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.7 on 2025-10-27 12:11."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create a minimal DataSource Model."""

    dependencies: ClassVar = [
        ("api", "0019_dependency"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=256)),
                ("owner", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="last_updated",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="api.assettype",
            ),
        ),
        migrations.AddField(
            model_name="assettype",
            name="data_source_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="types",
                to="api.datasource",
            ),
        ),
    ]
