"""Generated by Django 5.2.6 on 2025-10-28 16:10."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add external_id which links assets in dependency table."""

    dependencies: ClassVar = [
        ("api", "0020_datasources"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="asset",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="dependent_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependent",
                to="api.asset",
                to_field="external_id",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="provider_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider",
                to="api.asset",
                to_field="external_id",
            ),
        ),
    ]
