"""Generated by Django 5.2.6 on 2025-11-03 16:02."""

from typing import ClassVar

import django
from django.db import migrations, models


class Migration(migrations.Migration):
    """Link dependency table to external_id."""

    dependencies: ClassVar = [
        ("api", "0021_asset_external_id"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="asset",
            name="external_id",
            field=models.CharField(blank=True, default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="dependent_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependent",
                to="api.asset",
                to_field="external_id",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="provider_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider",
                to="api.asset",
                to_field="external_id",
            ),
        ),
    ]
