"""Generated by Django 5.2.8 on 2025-11-26 10:31."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the ExposureLayer model."""

    dependencies: ClassVar = [
        ("api", "0023_exposurelayer"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="assetsubcategory",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="api.assetcategory",
            ),
        ),
        migrations.AlterField(
            model_name="assettype",
            name="sub_category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_types",
                to="api.assetsubcategory",
            ),
        ),
    ]
