# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.8 on 2025-11-26 10:31."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Set related names for asset types and sub-categories."""

    dependencies: ClassVar = [
        ("api", "0023_exposurelayer"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="assetsubcategory",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="api.assetcategory",
            ),
        ),
        migrations.AlterField(
            model_name="assettype",
            name="sub_category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_types",
                to="api.assetsubcategory",
            ),
        ),
    ]
