# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.8 on 2025-12-03 09:26."""

import uuid
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create exposure layer type model."""

    dependencies: ClassVar = [
        ("api", "0024_assetcategory_related_names"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="ExposureLayerType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        )
    ]
