# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.8 on 2025-12-03 09:31."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create type foreign key for exposure layer."""

    dependencies: ClassVar = [
        ("api", "0025_exposurelayertype_exposurelayer_type"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="exposurelayer",
            name="type",
            field=models.ForeignKey(
                default="2d373dca-1337-4e60-ba08-c8326d27042d",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exposure_layers",
                to="api.exposurelayertype",
            ),
        ),
    ]
