# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.9 on 2025-12-05 15:31."""

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create ScenarioAsset models."""

    dependencies: ClassVar = [
        ("api", "0028_visibleexposurelayer"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="ScenarioAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("criticality_score", models.IntegerField()),
                (
                    "asset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_scores",
                        to="api.assettype",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_type_scores",
                        to="api.scenario",
                    ),
                ),
            ],
        ),
    ]
