# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.9 on 2025-12-09 10:58."""

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    """Create views to represent asset scores."""

    dependencies: ClassVar = [
        ("api", "0029_scenarioasset"),
    ]

    operations: ClassVar = [
        migrations.RunSQL(
            sql="""
                CREATE MATERIALIZED VIEW public.assets_within_500m_exposure_layers AS
                SELECT a.id AS asset_id,
                    e.id AS exposure_layer_id,
                    st_intersects(a.geom::geography, e.geometry::geography) AS intersects
                FROM api_asset a
                CROSS JOIN api_exposurelayer e
                WHERE ST_DWithin(a.geom::geography, e.geometry::geography, 500);
                CREATE INDEX api_assets_within_500m_exposure_layers_exposure_layer_id
                    ON public.assets_within_500m_exposure_layers (exposure_layer_id);
            """,
            reverse_sql="""
                DROP MATERIALIZED VIEW IF EXISTS public.assets_within_500m_exposure_layers;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE VIEW public.visible_exposure_asset_scores AS
                     WITH active_exposure_layers AS (
                            SELECT ael.asset_id,
                                ve.user_id,
                                ael.exposure_layer_id,
                                ael.intersects
                            FROM assets_within_500m_exposure_layers ael
                                JOIN api_visibleexposurelayer ve
                                    ON ael.exposure_layer_id = ve.exposure_layer_id
                            ), agg AS (
                            SELECT active_exposure_layers.asset_id, active_exposure_layers.user_id,
                                count(*) FILTER (WHERE active_exposure_layers.intersects)
                                    AS inter_ct,
                                count(*) FILTER (WHERE NOT active_exposure_layers.intersects)
                                    AS near_ct
                            FROM active_exposure_layers
                            GROUP BY active_exposure_layers.asset_id, active_exposure_layers.user_id
                            )
                    SELECT asset_id, user_id,
                            CASE
                                WHEN inter_ct > 1 THEN 3
                                WHEN inter_ct = 1 THEN 2
                                WHEN near_ct >= 1 THEN 1
                                ELSE 0
                            END AS score
                    FROM agg;
            """,
            reverse_sql="""
                DROP VIEW IF EXISTS public.visible_exposure_asset_scores;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE VIEW public.asset_scores AS
                    SELECT a.id,
                        s_a.scenario_id,
                        exposure.user_id,
                        s_a.criticality_score,
                        COALESCE(avg(dep_score.score), 0) AS dependency_score,
                        COALESCE(exposure.score, 0) AS exposure_score,
                        3 AS redundancy_score
                    FROM api_scenarioasset s_a
                        LEFT JOIN api_asset a ON a.type_id = s_a.asset_type_id
                        LEFT JOIN (
                            SELECT a_d.provider_asset_id AS id, s_a_1.criticality_score AS score
                            FROM api_dependency a_d
                            LEFT JOIN api_asset a_1
                                ON a_d.dependent_asset_id = a_1.external_id
                            LEFT JOIN api_scenarioasset s_a_1
                                ON s_a_1.asset_type_id = a_1.type_id
                    ) dep_score ON dep_score.id = a.external_id
                        LEFT JOIN (
                            SELECT veas.asset_id, veas.user_id, veas.score
                            FROM visible_exposure_asset_scores veas
                            UNION ALL SELECT veas.asset_id, NULL as user_id, 0 as score
                            FROM visible_exposure_asset_scores veas
                        ) exposure ON exposure.asset_id = a.id
                    GROUP BY a.id, s_a.scenario_id, exposure.user_id, s_a.criticality_score,
                        exposure.score;
            """,
            reverse_sql="""
                DROP VIEW IF EXISTS public.asset_scores;
            """,
        ),
    ]
