# Generated by Django 5.2.9 on 2025-12-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_update_asset_score_views_for_focus_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetScore',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('scenario_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('criticality_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dependency_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exposure_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redundancy_score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'asset_scores',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='assettype',
            name='icon',
            field=models.CharField(default='fa-tag', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
