"""Generated by Django 5.2.9 on 2025-12-22 13:51."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add icon field to asset_type relation."""

    dependencies: ClassVar = [
        ("api", "0037_add_scenario_code_and_active_constraint"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="assettype",
            name="icon",
            field=models.CharField(default="fa-tag", max_length=256),
        )
    ]
