# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.9 on 2025-12-29 11:43."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add description in markdown to datasource."""

    dependencies: ClassVar = [
        ("api", "0039_filter_exposure_not_impacting_cder_score"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="datasource",
            name="description_md",
            field=models.TextField(default=""),
        ),
    ]
