# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.9 on 2026-01-26 16:38."""

import uuid
from typing import ClassVar

from django.db import migrations, models
from django.utils import timezone


def set_created_at(apps, _schema_editor):
    """Set created_at timestamps for existing groups and group memberships."""
    Group = apps.get_model("api", "Group")
    Group.objects.filter(created_at__isnull=True).update(created_at=timezone.now())
    GroupMembership = apps.get_model("api", "GroupMembership")
    GroupMembership.objects.filter(created_at__isnull=True).update(created_at=timezone.now())


class Migration(migrations.Migration):
    """Add default pk to Group entities and make name mandatory."""

    dependencies: ClassVar = [
        ("api", "0048_add_constraint_intervention"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="groupdatasourceaccess",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.RunPython(set_created_at),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
