"""Generated by Django 5.2.9 on 2026-01-26 16:38."""

import uuid
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add default pk to Group entities and make name mandatory."""

    dependencies: ClassVar = [
        ("api", "0048_groups"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="groupdatasourceaccess",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
