# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.9 on 2026-01-27 14:29."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add uniqueness constraint to membership and ordering."""

    dependencies: ClassVar = [
        ("api", "0049_group_default_pks"),
    ]

    operations: ClassVar = [
        migrations.AlterModelOptions(
            name="groupmembership",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "user_id"), name="unique_membership_per_user"
            ),
        ),
    ]
