"""Generated by Django 5.2.9 on 2026-01-29 16:25."""

import uuid
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create user_invite relation."""

    dependencies: ClassVar = [
        ("api", "0050_group_ordering_and_uniqueness"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="UserInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
