# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Generated by Django 5.2.11 on 2026-02-04 11:50."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Rename user invite expiry field to expired_at."""

    dependencies: ClassVar = [
        ("api", "0052_user_invites"),
    ]

    operations: ClassVar = [
        migrations.RenameField(
            model_name="userinvite",
            old_name="expires_at",
            new_name="expired_at",
        ),
        migrations.AlterField(
            model_name="userinvite",
            name="user_id",
            field=models.UUIDField(unique=True),
        ),
    ]
