# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""Add ResourceIntervention models and VisibleResourceInterventionType."""

# Generated by Django 5.2.9 on 2026-02-06 10:47

import uuid
from typing import ClassVar

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add ResourceIntervention models and VisibleResourceInterventionType."""

    dependencies: ClassVar = [
        ("api", "0053_rename_user_invite_expiry_field"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="ResourceInterventionAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[("withdraw", "Withdraw"), ("restock", "Restock")], max_length=10
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceInterventionLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("current_stock", models.IntegerField(default=0)),
                ("max_capacity", models.IntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResourceInterventionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("unit", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VisibleResourceInterventionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name="resourceinterventionlocation",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_intervention_locations",
                to="api.scenario",
            ),
        ),
        migrations.AddField(
            model_name="resourceinterventionaction",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="api.resourceinterventionlocation",
            ),
        ),
        migrations.AddField(
            model_name="resourceinterventionlocation",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="api.resourceinterventiontype",
            ),
        ),
        migrations.AddField(
            model_name="visibleresourceinterventiontype",
            name="resource_intervention_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visible_in",
                to="api.resourceinterventiontype",
            ),
        ),
        migrations.AddField(
            model_name="visibleresourceinterventiontype",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visible_resource_intervention_types",
                to="api.scenario",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceinterventionaction",
            index=models.Index(
                fields=["location", "-created_at"], name="resource_action_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceinterventionaction",
            index=models.Index(fields=["user_id", "-created_at"], name="resource_action_user_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceinterventionlocation",
            index=models.Index(fields=["scenario", "name"], name="resource_loc_scenario_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="resourceinterventionlocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__gte", 0)),
                name="resource_location_stock_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceinterventionlocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__lte", models.F("max_capacity"))),
                name="resource_location_stock_within_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceinterventionlocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_capacity__gt", 0)),
                name="resource_location_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceinterventionaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="action_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="visibleresourceinterventiontype",
            constraint=models.UniqueConstraint(
                fields=("user_id", "scenario", "resource_intervention_type"),
                name="unique_visible_resource_intervention_type",
            ),
        ),
    ]
