"""Generated by Django 5.2.11 on 2026-02-09 12:39."""

import uuid
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add `created_by` to group data source access and default uuid IDs to other models."""

    dependencies: ClassVar = [
        ("api", "0054_resource_interventions"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="groupdatasourceaccess",
            name="created_by",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="assetsubcategory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="assettype",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
