"""Generated by Django 5.2.11 on 2026-02-16 15:19."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add status to exposure layer model."""

    dependencies: ClassVar = [
        ("api", "0055_data_source_access"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="exposurelayer",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("pending", "Pending"),
                    ("unpublished", "Unpublished"),
                ],
                default="unpublished",
                max_length=20,
            ),
        )
    ]
