"""Generated by Django 5.2.11 on 2026-02-16 15:19."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add status to exposure layer model."""

    dependencies: ClassVar = [
        ("api", "0056_asset_criticality_override"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="exposurelayer",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("unpublished", "Unpublished"),
                ],
                default="unpublished",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exposurelayer",
            name="approved_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exposurelayer",
            name="rejected_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exposurelayer",
            name="removed_by",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
