"""Generated by Django 5.2.11 on 2026-02-23 14:04."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add published_id_int field and sequence."""

    dependencies: ClassVar = [
        ("api", "0057_exposure_layer_publishing"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="exposurelayer",
            name="published_id_int",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunSQL(
            "CREATE SEQUENCE published_id_seq;",
            "DROP SEQUENCE published_id_seq;",
        ),
    ]
