apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vista-frontend-static-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vista-frontend-role
    serviceAccount: vista-frontend-sa
    audiences:
      - vault
