apiVersion: v1
kind: Service
metadata:
  namespace: paralog
  annotations:
    kompose.cmd: kompose convert -f ../docker_build/docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
    service.beta.kubernetes.io/aws-load-balancer-name: ${ENVIRONMENT}-ontology-api-nlb
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    io.kompose.service: ${ENVIRONMENT}-ontology-api
  name: ${ENVIRONMENT}-ontology-api
spec:
  type: LoadBalancer
  ports:
    - name: "5007"
      port: 5007
      targetPort: 5007
  selector:
    io.kompose.service: ${ENVIRONMENT}-ontology-api
