server {

  listen 8080;

  location ~ /vista {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri /vista/index.html;
  }
  location = / {
      return 301 /vista/;
  }
  error_page   500 502 503 504  /50x.html;

  location = /50x.html {
    root   /usr/share/nginx/html;
  }

}
