server {

  listen 8080;

  root   /usr/share/nginx/html;
  index  index.html index.htm;

  location = / {
      return 301 /vista/;
  }

  location /vista/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ @vista_spa_fallback;
  }

  location @vista_spa_fallback {
    alias /usr/share/nginx/html/index.html;
  }

  location = /vista {
    return 301 /vista/;
  }

  error_page   500 502 503 504  /50x.html;

  location = /50x.html {
    root   /usr/share/nginx/html;
  }

}
