resources:
  - ../../base

namespace: paralog
patches:

  - path: patches/allow-ingress.yaml
    target:
      kind: AuthorizationPolicy
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: paralog-python-api-sa

labels:
  - pairs:
      env: prod

images:
  - name: paralog-python-api-image
    newName: 537124944113.dkr.ecr.eu-west-2.amazonaws.com/paralog/python-api
    newTag: "to.be.replaced"

configMapGenerator:
  - name: paralog-python-api-configs
    envs:
      - params.env
