apiVersion: batch/v1
kind: Job
metadata:
  name: vista-python-api-job
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: vista-python-api-sa
      containers:
        - name: vista-python-api-image
          image: vista-python-api-image:template
          imagePullPolicy: Always
          command: ["./entrypoint.sh"]
          envFrom:
            - configMapRef:
                name: vista-python-api-configs
            - secretRef:
                name: vista-python-api-secret
          resources:
            requests:
              cpu: "0.5" # Minimum CPU your container is guaranteed.
              memory: "2Gi" # Minimum Memory your container is guaranteed.
              ephemeral-storage: "2Gi"
            limits:
              cpu: "3" # Maximum CPU your container can use.
              memory: "2Gi" # Maximum Memory your container can use.
      restartPolicy: Never
  ttlSecondsAfterFinished: 10
  backoffLimit: 4
