name: Paralog continuous deployment production

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: production_environment
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/cd-template.yml
    with:
      environment: "production"
    secrets:
      MAP_TILER_TOKEN: ${{ secrets.VITE_MAP_TILER_TOKEN }}
      ORDNANCE_SURVEY_API_KEY: ${{ secrets.ORDNANCE_SURVEY_API_KEY }}
      ADMIRALTY_API_KEY: ${{ secrets.ADMIRALTY_API_KEY }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SERVICE_AWS_ACCESS_KEY_ID: ${{ secrets.SERVICE_AWS_ACCESS_KEY_ID }}
      SERVICE_AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVICE_AWS_SECRET_ACCESS_KEY }}
      AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}
      REALTIME_TRAINS_API_KEY: ${{ secrets.REALTIME_TRAINS_API_KEY }}
      MET_OFFICE_GLOBAL_SPOT_API_KEY: ${{ secrets.MET_OFFICE_GLOBAL_SPOT_API_KEY }}
      CANNY_APP_ID: ${{ secrets.CANNY_APP_ID }}
      CANNY_BOARD_TOKEN: ${{ secrets.CANNY_BOARD_TOKEN }}
