name: Frontend CD push to ECR

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci-push-to-ecr.yml"
  workflow_call:
    inputs:
      aws_account_number:
        type: string
        required: true
        description: "AWS Account Number for ECR"
      repo_name:
        type: string
        required: true
        description: "Name of the repository in ECR"
      version:
        type: string
        required: false
        description: "Optional version number to skip version generation steps"
  workflow_dispatch:
    inputs:
      aws_account_number:
        type: string
        required: true
        description: "AWS Account Number for ECR"
      repo_name:
        type: string
        required: true
        description: "Name of the repository in ECR"
      version:
        type: string
        required: false
        description: "Optional version number to skip version generation steps"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install Dependencies
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Build Frontend
        working-directory: frontend
        run: yarn run build
        env:
          VITE_ONTOLOGY_SERVICE_URL: "/ontology"
          VITE_PARALOG_API_URL: "/paralog"
          VITE_MAP_TILER_TOKEN: "ABC123"
          VITE_MET_OFFICE_GLOBAL_SPOT_API_KEY: "XYZ123"

      - name: List Build Output
        working-directory: frontend
        run: ls -l dist/

  docker-build-push:
    name: Docker Build & Push
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build --load \
                        -t ${{ inputs.aws_account_number }}.dkr.ecr.eu-west-2.amazonaws.com/${{ inputs.repo_name }}:${{ github.sha }} \
                        -t ${{ inputs.aws_account_number }}.dkr.ecr.eu-west-2.amazonaws.com/${{ inputs.repo_name }}:latest \
                        -f frontend/Dockerfile ./frontend

      - name: List Built Docker Images
        run: docker images

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/ecs-access-for-github
          aws-region: eu-west-2
          role-session-name: githubsession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image to ECR
        run: |
          docker image push --all-tags ${{ inputs.aws_account_number }}.dkr.ecr.eu-west-2.amazonaws.com/${{ inputs.repo_name }}

      - name: Verify Docker Image in ECR
        run: |
          aws ecr describe-images --repository-name ${{ inputs.repo_name }} --query 'sort_by(imageDetails, &imagePushedAt)[-1]' --output table >> $GITHUB_STEP_SUMMARY

      - name: Cleanup Docker Images
        if: always()
        run: docker rmi -f $(docker images -q ${{ inputs.aws_account_number }}.dkr.ecr.eu-west-2.amazonaws.com/${{ inputs.repo_name }})
