name: Build and push telicent-paralog
on:
  push:
    branches:
      - main
      - "api-v2"
    paths:
      - CHANGELOG.md

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version from package.json
        id: semver
        uses: martinbeentjes/npm-get-version-action@main
    outputs:
      version: ${{ steps.semver.outputs.current-version }}

  integrated_tests:
    permissions:
      id-token: write
      contents: read
      packages: write
    needs: get_version
    env:
      APP_NAME: paralog
      NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
      FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: configure-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@Telicent-io"
          always-auth: true
      - name: create .yarnrc file
        run: |
          npm config set "@telicent-io:registry" "https://npm.pkg.github.com/"
          npm config set "//npm.pkg.github.com/:_authToken" ${{ secrets.PACKAGE_PAT }} 
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set  "//npm.fontawesome.com/:_authToken" ${{ secrets.FONT_AWESOME_KEY }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: mkdir reports
      - run: yarn test:ci
      - name: Configure AWS credentials from main account
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::098669589541:role/GitHubDeploymentRole
          aws-region: eu-west-2
      - name: Publish test logs to S3
        run: |
          aws s3 cp reports s3://telicent-deployment-${{ env.APP_NAME }}/${{ github.run_id }}-${{ needs.get_version.outputs.version }} --recursive

  publish_build_image_to_aws:
    needs:
      - integrated_tests
      - get_version
    uses: Telicent-io/telicent-test/.github/workflows/push-to-aws.yml@main
    with:
      APP_NAME: paralog
      DOCKERFILE: Dockerfile.build
      PATH: .
      VERSION: ${{ needs.get_version.outputs.version }}
      ECR_SUFFIX: -build
    secrets:
      NPM_TOKEN: ${{ secrets.PACKAGE_PAT }}
      FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_KEY }}

  publish_offline_image_to_aws:
    needs:
      - integrated_tests
      - get_version
      - publish_build_image_to_aws
    uses: Telicent-io/telicent-test/.github/workflows/push-to-aws.yml@main
    with:
      APP_NAME: paralog
      DOCKERFILE: Dockerfile.offline
      PATH: .
      VERSION: ${{ needs.get_version.outputs.version }}
      VERSION_SUFFIX: -offline
    secrets:
      NPM_TOKEN: ${{ secrets.PACKAGE_PAT }}
      FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_KEY }}

  publish_deployment_image_to_aws:
    needs:
      - integrated_tests
      - get_version
      - publish_build_image_to_aws
    uses: Telicent-io/telicent-test/.github/workflows/push-to-aws.yml@main
    with:
      APP_NAME: paralog
      DOCKERFILE: Dockerfile
      PATH: .
      VERSION: ${{ needs.get_version.outputs.version }}
    secrets:
      NPM_TOKEN: ${{ secrets.PACKAGE_PAT }}

  trigger_owasp_dependency_check-api:
    needs:
      # - publish_api_image_to_aws
      - publish_offline_image_to_aws
    uses: Telicent-io/telicent-test/.github/workflows/dependency_tracking.yml@main
    with:
      APP_NAME: paralog
