name: Publish Node Telicent image to Amazon ECR

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      DOCKERFILE:
        required: true
        type: string
      PATH:
        required: true
        type: string
      VERSION:
        required: true
        type: string
      VERSION_SUFFIX:
        required: false
        type: string
      ECR_SUFFIX:
        required: false
        type: string
    secrets:
      NPM_TOKEN:
        required: false
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from main account
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::098669589541:role/GitHubDeploymentRole
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: telicent-${{ inputs.APP_NAME }}${{ inputs.ECR_SUFFIX }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ${{ inputs.PATH }}
          echo 'version ===> ${{ inputs.VERSION }}${{ inputs.VERSION_SUFFIX }}'
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest${{ inputs.VERSION_SUFFIX }}  -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ inputs.VERSION }}${{ inputs.VERSION_SUFFIX }} --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} -f ${{ inputs.DOCKERFILE }} .
          docker image push --all-tags ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
