# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

name: Transparent Proxy CD - push to ECR

on:
  workflow_call:
    inputs:
      aws_account_number:
        type: string
        required: true
        description: "AWS Account Number for ECR"
      repo_name:
        type: string
        required: true
        description: "Name of the repository in ECR"
      app_name:
        type: string
        required: true
        description: "Name of app - frontend, backend or transparent-proxy"
      version:
        type: string
        required: true
        description: "Version number passed from main workflow"

  workflow_dispatch:
    inputs:
      aws_account_number:
        type: string
        required: true
        description: "AWS Account Number for ECR"
      repo_name:
        type: string
        required: true
        description: "Name of the repository in ECR"
      app_name:
        type: string
        required: true
        description: "Name of app - frontend, backend or transparent-proxy"
      version:
        type: string
        required: true
        description: "Version number passed from main workflow"

permissions:
  id-token: write
  contents: read
  packages: read
  statuses: write

jobs:
  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_ACCOUNT_NUMBER: ${{ inputs.aws_account_number }}
      REPO_NAME: ${{ inputs.repo_name }}
      APP_NAME: ${{ inputs.app_name }}
      VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Debug Version Output
        run: |
          echo "Using provided version: $VERSION"

      - name: Build Docker Image
        run: |
          ECR_REGISTRY="${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-2.amazonaws.com"
          docker build --load \
                        -t "${ECR_REGISTRY}/${REPO_NAME}:${GITHUB_SHA}" \
                        -t "${ECR_REGISTRY}/${REPO_NAME}:${VERSION}" \
                        -f "${APP_NAME}/Dockerfile" "./${APP_NAME}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/ecr-access-for-github
          aws-region: eu-west-2
          role-session-name: githubsession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image to ECR
        run: |
          ECR_REGISTRY="${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-2.amazonaws.com"
          docker image push --all-tags "${ECR_REGISTRY}/${REPO_NAME}"

      - name: Verify Docker Image
        run: |
          docker images
          aws ecr describe-images --repository-name "${REPO_NAME}" --query 'sort_by(imageDetails, &imagePushedAt)[-1]' --output table >> "$GITHUB_STEP_SUMMARY"
